// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"seta-training/internal/models"
)

type CreateUserInput struct {
	Username string          `json:"username"`
	Email    string          `json:"email"`
	Password string          `json:"password"`
	Role     models.UserRole `json:"role"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	User  *models.User `json:"user"`
	Token string       `json:"token"`
}

type Mutation struct {
}

type Query struct {
}
